
[[_grooscript]]
= Grooscript

This little framework is the engine of the plugin. It converts Groovy code to javascript.
You don't need to know Grooscript, the plugin do the work for you. But you can
take a look to http://grooscript.org/ to get more info. Grooscript compile the code,
inspect the AST tree, and generate the javascript code.

Just remember you need +grooscript-grails.js+ to run converted code. Add +<asset:javascript src="grooscript-grails.js"/+ to your gsp.

== Spring bean

There is *grooscriptConverter* bean, that you can inject in your grails artifacts:

[source,groovy]
--
class MyController {

    def grooscriptConverter

    def index() {
        def jsCode = grooscriptConverter.toJavascript('any groovy code')
    }
}
--

All conversion done with bean or tags, use classPath +''src/groovy''+ by default.

== Conversion daemon

You can activate the conversion daemon to convert groovy files to javascript while your application is up
in development. Each time you change observed groovy files, javascript file will be converted. To activate
this daemon have to configure in your +Config.groovy+:

[source,groovy]
--
grooscript {
    daemon {
        source = ['src/groovy'] //<1>
        destination = 'web-app/js' //<2>
    }
}
--
<1> List of groovy files or folders that will be converted to javascript.
<2> Destination folder of the javascript files.