
[[_templates]]
== <grooscript:template>

You can create html templates using this tag. A template is a piece of groovy code that will be
executed inside a html builder. So you generate javascript code that will run as a DSL(HtmlBuilder). In groovy exists
some html builders, this is a simple one, that is available inside grooscript js libs. For example:

[source,groovy]
--
<grooscript:template>
    ul {
        5.times { number ->
            li "${number} li item"
        }
    }
</grooscript:template>
--

The template is executed in the client, not in the server.

You can put templates in separates files if you want to.

You can define a jQuery selector with the elements that will be updated each time template renders.

You can execute the template at start or when you want.

The template can listen client events to renders again.

You can pass a parameter to template, variable 'data' is available inside the tag.

[source,groovy]
--
<div id="list"></div>

<grooscript:template renderOnReady="false" functionName="refreshList" itemSelector="#list">
    ul {
        data.each { book ->
            li {
                p 'Id: ' + book.id + ' Name: ' + book.title
            }
        }
    }
</grooscript:template>

<grooscript:code>
    $(document).ready({
        refreshList([[id: 1, title:'Groovy in Action'], [id: 2, title:'Grails in Action']])
    })
</grooscript:code>
--